[package]
authors = ["Johan Helsing <johanhelsing@gmail.com>"]
categories = ["game-development"]
description = "A camera that allows panning by dragging with the mouse"
edition = "2021"
keywords = ["gamedev", "bevy"]
license = "MIT OR Apache-2.0"
name = "bevy_pancam"
readme = "readme.md"
repository = "https://github.com/johanhelsing/bevy_pancam"
version = "0.6.1"

[features]
bevy_egui = ["dep:bevy_egui"]
bevy-inspector-egui = ["dep:bevy-inspector-egui"]

[dependencies]
bevy = {version = "0.8", features = ["render"], default-features = false}
bevy_egui = {version = "0.16", optional = true, default-features = false}
bevy-inspector-egui = { version = "0.12", optional = true, default-features = false }

[dev-dependencies]
bevy = {version = "0.8", default-features = false, features = [
  "render",
  "bevy_asset",
  "bevy_winit",
  "x11", # github actions runners don't have libxkbcommon installed, so can't use wayland
]}
rand = "0.8"
bevy_egui = {version = "0.16", default-features = false, features = ["default_fonts"]}
bevy-inspector-egui = {version = "0.12.1", default-features = false}

[[example]]
name = "egui"
required-features = ["bevy_egui"]

[[example]]
name = "inspector"
required-features = ["bevy-inspector-egui"]